### ISSUE TITLE
Please add a note about redirect-after-post 

### ISSUE THREAD

**Issue by guettli** [spookylukey/django-htmx-patterns#1]
Hi, thank you for your hints.

This pattern is usually used in Django:

https://en.m.wikipedia.org/wiki/Post/Redirect/Get

It's not needed if the form was submitted via htmx and a fragment gets returned.

Like in of your examples.

I think this should be elaborated, so that people learn that it's not needed.

Btw, I have a similar page, but a different point of view: https://github.com/guettli/django-htmx-fun
I don't like Django templates, since they hide exceptions.

**Comment by spookylukey** [comment]
That's a good point, I'll add it.

I'll also add a link to your page, thanks!
